---
title: "About me"
---

I was born and raised in Mexico City. I obtained a B.A. degree in Communication from Universidad Panamericana, where I later taught the *Quantitative Research in Communication* undergraduate course. After graduating college in 2018, I collaborated in numerous research consulting projects, mainly on gender and transparency issues. I used quantitative methods to evaluate public policy programs for Mexican institutions such as the National Institute for Information Access and the National Judiciary. In 2021 I became a Fulbright-García Robles grantee.  
<br>
My main academic interest is the representation of racial and skin color stereotypes in mass media. However, I've done research about various topics, including transparency, gender, globalization, and political identification. You can find my detailed professional and academic experience in my <a href="CV.pdf" download>CV</a>, and you can look at my publications <a href="https://scholar.google.com/citations?user=bEIbJF8AAAAJ&hl=en">here</a>.
<br>



